In [4]:
from collections import Counter
import numpy as np

In [2]:
data = np.loadtxt('./data/data.txt').astype(int)

In [3]:
# Loading the movie data
movie_data = np.genfromtxt('./data/movies.txt', dtype=None, delimiter='\t', encoding='utf8')

In [6]:
movie_titles = [movie[1] for movie in movie_data]

In [7]:
movie_dict = Counter(movie_titles)

In [11]:
movie_ids = {}

i = 1
for movie in movie_titles:
    movie_ids[i] = movie
    i += 1

In [13]:
movie_to_new_ids = {}

i = 1
for movie in movie_dict.keys():
    movie_to_new_ids[movie] = i
    i += 1

In [10]:
print(data)

[[ 196  242    3]
 [ 186  302    3]
 [  22  377    1]
 ...
 [ 276 1090    1]
 [  13  225    2]
 [  12  203    3]]


In [46]:
new_data = []

for rating in data:
    new_rating = [str(rating[0]), 0, str(rating[2])]
    new_rating[1] = str(movie_to_new_ids[movie_ids[rating[1]]])
    new_data.append(new_rating)

In [49]:
with open('./data/data_parsed.txt', 'w') as file:
    file.writelines('\t'.join(i) + '\n' for i in new_data)

In [28]:
train_data = np.loadtxt('./data/train.txt').astype(int)
test_data = np.loadtxt('./data/test.txt').astype(int)

In [30]:
new_train_data = []

for rating in train_data:
    new_rating = [str(rating[0]), 0, str(rating[2])]
    new_rating[1] = str(movie_to_new_ids[movie_ids[rating[1]]])
    new_train_data.append(new_rating)

In [39]:
with open('./data/train_parsed.txt', 'w') as file:
    file.writelines('\t'.join(i) + '\n' for i in new_train_data)

In [37]:
new_test_data = []

for rating in test_data:
    new_rating = [str(rating[0]), 0, str(rating[2])]
    new_rating[1] = str(movie_to_new_ids[movie_ids[rating[1]]])
    new_test_data.append(new_rating)

In [40]:
with open('./data/test_parsed.txt', 'w') as file:
    file.writelines('\t'.join(i) + '\n' for i in new_test_data)

In [50]:
data_formatted = np.loadtxt('./data/data_parsed.txt').astype(int)

In [55]:
print(data_formatted)

[[ 196  242    3]
 [ 186  301    3]
 [  22  374    1]
 ...
 [ 276 1081    1]
 [  13  225    2]
 [  12  203    3]]


In [52]:
train_formatted = np.loadtxt('./data/train_parsed.txt').astype(int)

In [53]:
train_formatted

array([[ 196,  242,    3],
       [ 186,  301,    3],
       [  22,  374,    1],
       ...,
       [ 716,  204,    5],
       [ 276, 1081,    1],
       [  12,  203,    3]])